"""empty message

Revision ID: 40470d468dcd
Revises: 
Create Date: 2020-03-05 15:39:56.806266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40470d468dcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=False)
    op.create_index(op.f('ix_guest_phone_number'), 'guest', ['phone_number'], unique=True)
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_capacity'), 'table', ['capacity'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('num_guests', sa.Integer(), nullable=True),
    sa.Column('reservation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_num_guests'), 'reservation', ['num_guests'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_time'), 'reservation', ['reservation_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_reservation_time'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_num_guests'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_table_capacity'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_guest_phone_number'), table_name='guest')
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
